// get all dinos DONE
GET http://localhost:3000/velocishop/products HTTP/1.1

###

// create customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{"customerId":16, "customerName": "Ana Peterson"}
###

###

// create basket for specific costumer 
POST http://localhost:3000/velocishop/customers/2/baskets HTTP/1.1
content-type: application/json

{"Id":3, "costumerId":3, "products":[]}
###

// get dino by id DONE
GET http://localhost:3000/velocishop/products/15 HTTP/1.1

###

// update customer
PUT  http://localhost:3000/customers/15 HTTP/1.1
content-type: application/json

{"customerId":15, "customerName": "John Johnson UPDATED!"}
###

// delete customer
DELETE  http://localhost:3000/customers/15 HTTP/1.1

###